# Generated by Django 4.2.3 on 2023-07-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
    ]
